import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import api, { apiError, unwrap } from '../services/api';
import { useAuth } from '../context/AuthContext';
import Notice from '../components/Notice';
import StatusBadge from '../components/StatusBadge';

const money = (value) => `₦${Number(value || 0).toLocaleString()}`;
const date = (value) => new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
function Loading({ children = 'Loading...' }) { return <div className="loading"><span className="spinner" />{children}</div>; }
function PageTitle({ eyebrow, title, children }) { return <div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{children}</div>; }

export function Dashboard() { const { user } = useAuth(); const [trips, setTrips] = useState([]); const [tickets, setTickets] = useState([]); const [error, setError] = useState(''); useEffect(() => { Promise.all([api.get('/api/trips'), api.get('/api/tickets/my-tickets')]).then(([tripResponse, ticketResponse]) => { setTrips(unwrap(tripResponse).data || []); setTickets(unwrap(ticketResponse).data || []); }).catch((err) => setError(apiError(err))); }, []); return <main className="page-shell"><PageTitle eyebrow="PASSENGER DASHBOARD" title={`Good to see you, ${user?.name?.split(' ')[0] || 'traveller'}.`}><Link className="button button-primary" to="/trips">Find a trip</Link></PageTitle><Notice>{error}</Notice><section className="dashboard-grid"><div className="feature-panel"><p className="eyebrow">NEXT DEPARTURES</p><h2>Make your move.</h2><p>Browse scheduled trips and book your seat when the route feels right.</p><Link className="button button-dark" to="/trips">Explore trips</Link></div><div className="metric-panel"><span className="metric-label">Scheduled trips</span><strong>{trips.filter((trip) => trip.status === 'scheduled').length}</strong><span>available in the network</span></div><div className="metric-panel accent"><span className="metric-label">Tickets held</span><strong>{tickets.length}</strong><span>in your travel history</span></div></section><section className="section-block"><div className="section-heading"><div><p className="eyebrow">YOUR LAST TICKETS</p><h2>Travel history</h2></div><Link to="/tickets">View all</Link></div>{tickets.length ? <div className="ticket-list">{tickets.slice(0, 3).map((ticket) => <TicketCard ticket={ticket} key={ticket._id} />)}</div> : <div className="empty-state">Your booked tickets will appear here.</div>}</section></main>; }

function TicketCard({ ticket }) { const route = ticket.trip?.route; return <article className="ticket-card"><div><span className="ticket-ref">{ticket.ticketReference}</span><h3>{route?.origin} <span>→</span> {route?.destination}</h3><p>{ticket.trip ? date(ticket.trip.departureTime) : 'Trip details unavailable'}</p></div><div className="ticket-side"><strong>{money(ticket.amount)}</strong><StatusBadge value={ticket.status} /></div></article>; }

export function Trips() { const [trips, setTrips] = useState([]); const [filters, setFilters] = useState({ search: '', status: 'scheduled' }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { setLoading(true); api.get('/api/trips', { params: filters.status ? { status: filters.status } : {} }).then((response) => setTrips(unwrap(response).data || [])).catch((err) => setError(apiError(err))).finally(() => setLoading(false)); }, [filters.status]); const visible = trips.filter((trip) => { const value = `${trip.route?.origin} ${trip.route?.destination}`.toLowerCase(); return value.includes(filters.search.toLowerCase()); }); return <main className="page-shell"><PageTitle eyebrow="PLAN A JOURNEY" title="Find your next trip"><div className="filter-row"><input aria-label="Search trips" placeholder="Search origin or destination" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}><option value="scheduled">Scheduled</option><option value="">All statuses</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div></PageTitle><Notice>{error}</Notice>{loading ? <Loading>Loading trips...</Loading> : visible.length ? <div className="trip-grid">{visible.map((trip) => <TripCard trip={trip} key={trip._id} />)}</div> : <div className="empty-state">No trips match this search.</div>}</main>; }
function TripCard({ trip }) { const navigate = useNavigate(); const route = trip.route || {}; return <article className="trip-card"><div className="trip-card-top"><StatusBadge value={trip.status} /><span>{trip.availableSeats} seats left</span></div><h2>{route.origin} <span>→</span> {route.destination}</h2><div className="trip-times"><div><small>DEPARTS</small><strong>{date(trip.departureTime)}</strong></div><div><small>ARRIVES</small><strong>{date(trip.arrivalTime)}</strong></div></div><div className="trip-footer"><div><small>FARE</small><strong>{money(route.fare)}</strong></div><button className="button button-primary" disabled={trip.status !== 'scheduled' || trip.availableSeats < 1} onClick={() => navigate(`/trips/${trip._id}`)}>View trip</button></div></article>; }

export function TripDetails() { const id = window.location.pathname.split('/').pop(); const navigate = useNavigate(); const [trip, setTrip] = useState(null); const [state, setState] = useState({ loading: true, booking: false, error: '', success: '' }); useEffect(() => { api.get(`/api/trips/${id}`).then((response) => setTrip(unwrap(response).data)).catch((err) => setState({ ...state, error: apiError(err) })).finally(() => setState((current) => ({ ...current, loading: false }))); }, [id]); const book = async () => { setState({ ...state, booking: true, error: '', success: '' }); try { const data = unwrap(await api.post('/api/tickets/createticket', { trip: id })); setState({ ...state, booking: false, success: data.message }); setTimeout(() => navigate('/tickets'), 1000); } catch (error) { setState({ ...state, booking: false, error: apiError(error) }); } }; if (state.loading) return <main className="page-shell"><Loading>Loading trip...</Loading></main>; if (!trip) return <main className="page-shell"><Notice>{state.error || 'Trip not found.'}</Notice></main>; const route = trip.route || {}; return <main className="page-shell narrow"><Link className="back-link" to="/trips">← Back to trips</Link><div className="detail-panel"><div className="detail-header"><div><p className="eyebrow">TRIP DETAILS</p><h1>{route.origin} <span>→</span> {route.destination}</h1></div><StatusBadge value={trip.status} /></div><Notice type="success">{state.success}</Notice><Notice>{state.error}</Notice><div className="detail-grid"><div><small>DEPARTURE</small><strong>{date(trip.departureTime)}</strong></div><div><small>ARRIVAL</small><strong>{date(trip.arrivalTime)}</strong></div><div><small>AVAILABLE SEATS</small><strong>{trip.availableSeats}</strong></div><div><small>FARE</small><strong className="fare">{money(route.fare)}</strong></div></div><button className="button button-primary wide" disabled={state.booking || trip.status !== 'scheduled' || trip.availableSeats < 1} onClick={book}>{state.booking ? 'Booking ticket...' : 'Book this trip'}</button></div></main>; }

export function Tickets() { const [tickets, setTickets] = useState([]); const [state, setState] = useState({ loading: true, error: '' }); useEffect(() => { api.get('/api/tickets/my-tickets').then((response) => setTickets(unwrap(response).data || [])).catch((err) => setState({ loading: false, error: apiError(err) })).finally(() => setState((current) => ({ ...current, loading: false }))); }, []); return <main className="page-shell"><PageTitle eyebrow="YOUR WALLET" title="My tickets"><Link className="button button-primary" to="/trips">Book a trip</Link></PageTitle><Notice>{state.error}</Notice>{state.loading ? <Loading>Loading tickets...</Loading> : tickets.length ? <div className="ticket-list">{tickets.map((ticket) => <TicketCard ticket={ticket} key={ticket._id} />)}</div> : <div className="empty-state"><h2>No tickets yet</h2><p>Choose a trip and your first ticket will be saved here.</p><Link className="button button-primary" to="/trips">Find a trip</Link></div>}</main>; }
